

export const kinds = [
    "articulo_revista"
  , "capitulo_libro"
  , "composicion"
  , "evento"
  , "exposicion"
  , "grabacion"
  , "informe_tecnico"
  , "libro"
  , "memoria"
  , "partitura"
  , "patente"
  , "premio"
  , "premio_bienal"
  , "proyecto_grado"
  , "proyecto_investigacion"
  , "recital"
];

export const detailed_kinds = [
  "ACTIVIDAD INVALIDA"
  , "Publicaciones en Revistas Indexadas en el SCI-SSCI-ARTS"
  , "Publicaciones en Revistas Indexadas en Otros Indices"
  , "Publicaciones en Revistas Arbitradas No Indexadas"
  , "Articulos Aceptados en Vías de Publicación"
  , "Publicaciones en Revistas Arbitradas"
  , "Publicaciones de Capítulos de Libros"
  , "Composiciones Solicitadas por Orquestas Sinfónicas o Agrupaciones Reconocidas"
  , "Asistencia a Eventos Internacionales"
  , "Asistencia a Eventos Nacionales"
  , "Eventos en Venezuela"
  , "Eventos en el Exterior"
  , "Eventos"
  , "Selección en Exposiciones, Bienales, Salones o Concursos Arbitrados"
  , "Grabaciones Sonoras Evaluadas Por Árbitros"
  , "Informes Técnicos"
  , "Libro Nacional"
  , "Libro Internacional"
  , "Publicaciones de Libros"
  , "Memorias *Arbitradas* de Congresos"
  , "Partituras, Video o CD's Publicados en Editoriales Reconocidas"
  , "Patentes Nacional"
  , "Patentes Internacional"
  , "Patentes"
  , "Premios"
  , "Trabajos Reconocidos o Premiados En Bienales, Salones, Concursos o Exposiciones"
  , "Tutoría de Tesis Doctorales"
  , "Tutoría de Trabajos de Grado (Mestrías)"
  , "Tutoría de Proyectos de Grado (Especializaciones)"
  , "Proyectos de Grado (Postgrados)"
  , "Tutoría de Proyectos de Grado (Licencituras)"
  , "Tutoría de Proyectos de Grado (Ingenierías)"
  , "Proyectos de Grado (Pasantías Largas)"
  , "Proyectos de Grado Dirigidos"
  , "Proyectos de IYD (Vigentes)"
  , "Proyectos de IYD"
  , "Recitales o Conciertos Arbitrados"
];
